export const danantiriABI = [
  {
    inputs: [{ internalType: "address", name: "_tokenAddress", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "programId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "FundAllocated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "sender", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "FundSent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "programId", type: "uint256" },
      { indexed: true, internalType: "address", name: "pic", type: "address" },
      { indexed: false, internalType: "string", name: "history", type: "string" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "FundWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "programId", type: "uint256" },
      { indexed: false, internalType: "string", name: "name", type: "string" },
      { indexed: false, internalType: "uint256", name: "target", type: "uint256" },
      { indexed: false, internalType: "address", name: "pic", type: "address" },
    ],
    name: "ProgramCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "programId", type: "uint256" },
      { indexed: false, internalType: "string", name: "name", type: "string" },
      { indexed: false, internalType: "string", name: "desc", type: "string" },
      { indexed: false, internalType: "address", name: "pic", type: "address" },
    ],
    name: "ProgramUpdated",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "_programId", type: "uint256" }],
    name: "allocateFund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "uint256", name: "_target", type: "uint256" },
      { internalType: "string", name: "_desc", type: "string" },
      { internalType: "address", name: "_pic", type: "address" },
    ],
    name: "createProgram",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllProgram",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "string", name: "name", type: "string" },
          { internalType: "uint256", name: "target", type: "uint256" },
          { internalType: "string", name: "desc", type: "string" },
          { internalType: "address", name: "pic", type: "address" },
          { internalType: "enum Danantiri.ProgramStatus", name: "status", type: "uint8" },
          { internalType: "uint256", name: "allocated", type: "uint256" },
        ],
        internalType: "struct Danantiri.Program[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_programId", type: "uint256" }],
    name: "getProgramHistory",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "timestamp", type: "uint256" },
          { internalType: "string", name: "history", type: "string" },
          { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        internalType: "struct Danantiri.History[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "idrxToken",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "programHistories",
    outputs: [
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "string", name: "history", type: "string" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "programs",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "target", type: "uint256" },
      { internalType: "string", name: "desc", type: "string" },
      { internalType: "address", name: "pic", type: "address" },
      { internalType: "enum Danantiri.ProgramStatus", name: "status", type: "uint8" },
      { internalType: "uint256", name: "allocated", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "sendFund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalAllocated",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalManagedFund",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_programId", type: "uint256" },
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "string", name: "_desc", type: "string" },
      { internalType: "address", name: "_pic", type: "address" },
    ],
    name: "updateProgram",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_programId", type: "uint256" },
      { internalType: "string", name: "_history", type: "string" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "withdrawFund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
